name: v2-hs-lib
version: 0.1.0.0
github: "oktana-coop/v2-hs-lib"
license: GPL-3.0
author: "Aris Goudouras"
maintainer: "aris.gk@gmail.com"
copyright: "2025 Aris Goudouras"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/oktana-coop/v2-hs-lib#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - name: pandoc-diff
      path: ../pandoc-diff
    - name: pandoc-tree
      path: ../pandoc-tree
    - aeson >= 2.2.3.0
    - bytestring >= 0.12.1.0
    - containers >= 0.7
    - mtl >= 2.3.1
    - pandoc >= 3.5
    - pandoc-types >= 1.23.1
    - text >= 2.1.1
  exposed-modules:
    - ProseMirror.Diff
    - ProseMirror.PandocWriter
    - ProseMirror.PandocReader
  other-modules:
    - ProseMirror.Model
    - ProseMirror.Decoration
    - ProseMirror.Tree
    - ProseMirror.Utils.Debug
    - ProseMirror.Utils.Json

executables:
  v2-hs-lib:
    main: Main.hs
    source-dirs: app
    dependencies:
      - v2-hs-lib
      - name: automerge-pandoc
        path: ../automerge-pandoc
      - name: pandoc-diff
        path: ../pandoc-diff
      - aeson >= 2.2.3.0
      - bytestring >= 0.12.1.0
      - exceptions >= 0.10.7
      - mtl >= 2.3.1
      - text >= 2.1.1
      - pandoc >= 3.5
      - optparse-applicative >= 0.18.1.0

tests:
  v2-hs-lib-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - v2-hs-lib
      - aeson >= 2.2.3.0
      - bytestring >= 0.12.1.0
      - filepath >= 1.5.2.0
      - pandoc >= 3.5
      - tasty >= 1.5.3
      - tasty-golden >= 2.3.5
      - text >= 2.1.1
      - v2-hs-lib
